"""
Mapping of Sydney suburb names and postcodes → store slugs.

Woolworths and Coles are available across all Sydney.
Harris Farm is included for suburbs near their store locations.
IGA variants are included only for the North Sydney / Lower North Shore area
where those specific stores are configured.
"""

_W = "woolworths"
_C = "coles"
_HF = "harris_farm"
_IN = "iga_north_sydney"
_IM = "iga_milsons_point"
_IC = "iga_crows_nest"

SUBURB_STORES: dict[str, list[str]] = {

    # ── City / CBD (2000) ─────────────────────────────────────────────
    "sydney":               [_W, _C, _HF],
    "sydney cbd":           [_W, _C, _HF],
    "haymarket":            [_W, _C, _HF],
    "the rocks":            [_W, _C],
    "barangaroo":           [_W, _C],
    "2000":                 [_W, _C, _HF],

    # ── Pyrmont / Ultimo (2007–2009) ──────────────────────────────────
    "pyrmont":              [_W, _C, _HF],
    "ultimo":               [_W, _C, _HF],
    "2007":                 [_W, _C, _HF],
    "2009":                 [_W, _C, _HF],

    # ── Inner East (2010–2021) ────────────────────────────────────────
    "surry hills":          [_W, _C, _HF],
    "darlinghurst":         [_W, _C, _HF],
    "east sydney":          [_W, _C, _HF],
    "woolloomooloo":        [_W, _C, _HF],
    "potts point":          [_W, _C, _HF],
    "elizabeth bay":        [_W, _C, _HF],
    "2010":                 [_W, _C, _HF],
    "redfern":              [_W, _C, _HF],
    "waterloo":             [_W, _C, _HF],
    "zetland":              [_W, _C, _HF],
    "2016":                 [_W, _C, _HF],
    "2017":                 [_W, _C, _HF],
    "paddington":           [_W, _C, _HF],
    "woollahra":            [_W, _C, _HF],
    "edgecliff":            [_W, _C, _HF],
    "2021":                 [_W, _C, _HF],

    # ── Eastern Suburbs (2022–2036) ───────────────────────────────────
    "double bay":           [_W, _C, _HF],
    "point piper":          [_W, _C],
    "rose bay":             [_W, _C, _HF],
    "bellevue hill":        [_W, _C, _HF],
    "2022":                 [_W, _C, _HF],
    "bondi junction":       [_W, _C, _HF],
    "bondi":                [_W, _C, _HF],
    "bondi beach":          [_W, _C, _HF],
    "tamarama":             [_W, _C],
    "bronte":               [_W, _C, _HF],
    "2026":                 [_W, _C, _HF],
    "waverley":             [_W, _C, _HF],
    "dover heights":        [_W, _C],
    "2024":                 [_W, _C, _HF],
    "clovelly":             [_W, _C],
    "coogee":               [_W, _C, _HF],
    "randwick":             [_W, _C, _HF],
    "2031":                 [_W, _C, _HF],
    "kingsford":            [_W, _C],
    "kensington":           [_W, _C, _HF],
    "2032":                 [_W, _C, _HF],
    "matraville":           [_W, _C],
    "malabar":              [_W, _C],
    "maroubra":             [_W, _C, _HF],
    "2035":                 [_W, _C, _HF],
    "la perouse":           [_W, _C],
    "phillip bay":          [_W, _C],
    "2036":                 [_W, _C],

    # ── Inner West (2037–2050) ────────────────────────────────────────
    "glebe":                [_W, _C, _HF],
    "forest lodge":         [_W, _C, _HF],
    "2037":                 [_W, _C, _HF],
    "rozelle":              [_W, _C, _HF],
    "lilyfield":            [_W, _C, _HF],
    "2039":                 [_W, _C, _HF],
    "balmain":              [_W, _C, _HF],
    "balmain east":         [_W, _C, _HF],
    "birchgrove":           [_W, _C, _HF],
    "2041":                 [_W, _C, _HF],
    "newtown":              [_W, _C, _HF],
    "erskineville":         [_W, _C, _HF],
    "2042":                 [_W, _C, _HF],
    "enmore":               [_W, _C, _HF],
    "st peters":            [_W, _C, _HF],
    "sydenham":             [_W, _C],
    "tempe":                [_W, _C],
    "2044":                 [_W, _C, _HF],
    "leichhardt":           [_W, _C, _HF],
    "annandale":            [_W, _C, _HF],
    "2040":                 [_W, _C, _HF],
    "petersham":            [_W, _C, _HF],
    "lewisham":             [_W, _C],
    "stanmore":             [_W, _C, _HF],
    "2048":                 [_W, _C, _HF],
    "marrickville":         [_W, _C, _HF],
    "dulwich hill":         [_W, _C, _HF],
    "2204":                 [_W, _C, _HF],
    "ashfield":             [_W, _C, _HF],
    "summer hill":          [_W, _C, _HF],
    "2131":                 [_W, _C, _HF],

    # ── Alexandria / Green Square / Zetland ───────────────────────────
    "alexandria":           [_W, _C, _HF],
    "beaconsfield":         [_W, _C],
    "rosebery":             [_W, _C, _HF],
    "green square":         [_W, _C, _HF],
    "2015":                 [_W, _C, _HF],
    "mascot":               [_W, _C],
    "eastlakes":            [_W, _C],
    "2018":                 [_W, _C],
    "botany":               [_W, _C],
    "2019":                 [_W, _C],

    # ── Lower North Shore (2060–2090) — includes IGA stores ───────────
    "north sydney":         [_W, _C, _IN],
    "lavender bay":         [_W, _C, _IN],
    "mcmahons point":       [_W, _C, _IN],
    "waverton":             [_W, _C, _IN],
    "berry island":         [_W, _C, _IN],
    "2060":                 [_W, _C, _IN],
    "milsons point":        [_W, _C, _IM],
    "kirribilli":           [_W, _C, _IM],
    "2061":                 [_W, _C, _IM],
    "cammeray":             [_W, _HF, _IN],
    "2062":                 [_W, _HF, _IN],
    "cremorne":             [_W, _C],
    "cremorne point":       [_W, _C],
    "2063":                 [_W, _C],
    "artarmon":             [_W, _C, _IC],
    "st leonards":          [_W, _C, _IC],
    "2064":                 [_W, _C, _IC],
    "crows nest":           [_W, _C, _IC],
    "wollstonecraft":       [_W, _C, _IC],
    "naremburn":            [_W, _C, _IC],
    "2065":                 [_W, _C, _IC],
    "lane cove":            [_W, _C],
    "longueville":          [_W, _C],
    "2067":                 [_W, _C],
    "mosman":               [_W, _C, _HF],
    "2088":                 [_W, _C, _HF],
    "neutral bay":          [_W, _C, _IM],
    "kurraba point":        [_W, _C, _IM],
    "2090":                 [_W, _C, _IM],

    # ── Upper North Shore ─────────────────────────────────────────────
    "chatswood":            [_W, _C, _HF],
    "willoughby":           [_W, _C],
    "castle cove":          [_W, _C],
    "2068":                 [_W, _C, _HF],
    "roseville":            [_W, _C, _HF],
    "lindfield":            [_W, _C],
    "2069":                 [_W, _C, _HF],
    "killara":              [_W, _C],
    "gordon":               [_W, _C],
    "pymble":               [_W, _C],
    "2071":                 [_W, _C],
    "turramurra":           [_W, _C],
    "warrawee":             [_W, _C],
    "2074":                 [_W, _C],
    "wahroonga":            [_W, _C],
    "2076":                 [_W, _C],
    "hornsby":              [_W, _C],
    "waitara":              [_W, _C],
    "2077":                 [_W, _C],
    "st ives":              [_W, _C],
    "2075":                 [_W, _C],

    # ── Northern Beaches ──────────────────────────────────────────────
    "manly":                [_W, _C, _HF],
    "fairlight":            [_W, _C, _HF],
    "2095":                 [_W, _C, _HF],
    "freshwater":           [_W, _C, _HF],
    "curl curl":            [_W, _C],
    "2096":                 [_W, _C, _HF],
    "dee why":              [_W, _C, _HF],
    "2099":                 [_W, _C, _HF],
    "narraweena":           [_W, _C],
    "brookvale":            [_W, _C, _HF],
    "2100":                 [_W, _C, _HF],
    "narrabeen":            [_W, _C],
    "collaroy":             [_W, _C],
    "2101":                 [_W, _C],
    "avalon beach":         [_W, _C],
    "avalon":               [_W, _C],
    "bilgola":              [_W, _C],
    "2107":                 [_W, _C],
    "mona vale":            [_W, _C],
    "2103":                 [_W, _C],
    "frenchs forest":       [_W, _C, _HF],
    "2086":                 [_W, _C, _HF],

    # ── North West / Hills District ───────────────────────────────────
    "ryde":                 [_W, _C],
    "west ryde":            [_W, _C],
    "meadowbank":           [_W, _C],
    "2112":                 [_W, _C],
    "epping":               [_W, _C],
    "2121":                 [_W, _C],
    "carlingford":          [_W, _C],
    "2118":                 [_W, _C],
    "castle hill":          [_W, _C],
    "2154":                 [_W, _C],
    "baulkham hills":       [_W, _C],
    "2153":                 [_W, _C],
    "kellyville":           [_W, _C],
    "2155":                 [_W, _C],
    "norwest":              [_W, _C],
    "bella vista":          [_W, _C],

    # ── Parramatta / West ─────────────────────────────────────────────
    "parramatta":           [_W, _C],
    "2150":                 [_W, _C],
    "westmead":             [_W, _C],
    "2145":                 [_W, _C],
    "pendle hill":          [_W, _C],
    "2145":                 [_W, _C],
    "granville":            [_W, _C],
    "2142":                 [_W, _C],
    "auburn":               [_W, _C],
    "2144":                 [_W, _C],
    "merrylands":           [_W, _C],
    "2160":                 [_W, _C],
    "liverpool":            [_W, _C],
    "2170":                 [_W, _C],
    "campbelltown":         [_W, _C],
    "2560":                 [_W, _C],

    # ── Strathfield / Burwood / Inner West ────────────────────────────
    "strathfield":          [_W, _C],
    "2135":                 [_W, _C],
    "burwood":              [_W, _C],
    "2134":                 [_W, _C],
    "concord":              [_W, _C],
    "2137":                 [_W, _C],
    "homebush":             [_W, _C],
    "homebush bay":         [_W, _C],
    "2140":                 [_W, _C],
    "five dock":            [_W, _C, _HF],
    "canada bay":           [_W, _C],
    "2046":                 [_W, _C, _HF],
    "drummoyne":            [_W, _C, _HF],
    "2047":                 [_W, _C, _HF],

    # ── St George / Sutherland ────────────────────────────────────────
    "kogarah":              [_W, _C],
    "2217":                 [_W, _C],
    "hurstville":           [_W, _C],
    "2220":                 [_W, _C],
    "rockdale":             [_W, _C],
    "2216":                 [_W, _C],
    "brighton-le-sands":    [_W, _C],
    "ramsgate":             [_W, _C],
    "2217":                 [_W, _C],
    "miranda":              [_W, _C],
    "2228":                 [_W, _C],
    "cronulla":             [_W, _C],
    "2230":                 [_W, _C],
    "sutherland":           [_W, _C],
    "2232":                 [_W, _C],

    # ── Chifley / South East ──────────────────────────────────────────
    "little bay":           [_W, _C],
    "chifley":              [_W, _C],
    "port botany":          [_W, _C],
    "2036":                 [_W, _C],

    # ── Newtown / Enmore adjacent ─────────────────────────────────────
    "camperdown":           [_W, _C, _HF],
    "2050":                 [_W, _C, _HF],

}

# Sorted list of suburb names only (no postcodes), for reference
ALL_SUBURBS = sorted(
    {k for k in SUBURB_STORES if not k.isdigit()},
    key=str.lower,
)

# Mapping of postcode → primary suburb name(s) for display
POSTCODE_NAMES: dict[str, str] = {
    "2000": "Sydney CBD",
    "2007": "Pyrmont / Ultimo",
    "2009": "Pyrmont",
    "2010": "Surry Hills / Darlinghurst",
    "2015": "Alexandria / Green Square",
    "2016": "Redfern / Waterloo",
    "2017": "Waterloo / Zetland",
    "2018": "Mascot / Eastlakes",
    "2019": "Botany",
    "2021": "Paddington / Woollahra",
    "2022": "Bondi / Double Bay",
    "2024": "Waverley / Dover Heights",
    "2026": "Bondi Beach / Bronte",
    "2031": "Coogee / Randwick",
    "2032": "Kingsford / Kensington",
    "2035": "Maroubra",
    "2036": "La Perouse / Chifley",
    "2037": "Glebe / Forest Lodge",
    "2039": "Rozelle / Lilyfield",
    "2040": "Leichhardt / Annandale",
    "2041": "Balmain",
    "2042": "Newtown / Erskineville",
    "2044": "Enmore / St Peters",
    "2046": "Drummoyne",
    "2047": "Drummoyne",
    "2048": "Petersham / Stanmore",
    "2050": "Camperdown / Newtown",
    "2060": "North Sydney",
    "2061": "Milsons Point / Kirribilli",
    "2062": "Cammeray",
    "2063": "Cremorne",
    "2064": "Artarmon / St Leonards",
    "2065": "Crows Nest / Wollstonecraft",
    "2067": "Chatswood",
    "2068": "Lane Cove / Longueville",
    "2069": "Ryde / Meadowbank",
    "2071": "Killara / Gordon",
    "2074": "Pymble / Turramurra",
    "2075": "St Ives",
    "2076": "Hornsby / Waitara",
    "2077": "Asquith / Berowra",
    "2086": "Frenchs Forest / Forestville",
    "2088": "Mosman",
    "2090": "Neutral Bay / Cremorne",
    "2095": "Manly",
    "2096": "Dee Why / Brookvale",
    "2099": "Narrabeen / Collaroy",
    "2100": "Allambie Heights / Beacon Hill",
    "2101": "Mona Vale / Bayview",
    "2103": "Church Point / Scotland Island",
    "2107": "Palm Beach / Avalon",
    "2112": "Rhodes / Concord",
    "2118": "Cherrybrook / Pennant Hills",
    "2121": "Epping / Carlingford",
    "2131": "Ashfield / Summer Hill",
    "2134": "Burwood",
    "2135": "Strathfield",
    "2137": "Concord / Rhodes",
    "2140": "Homebush / Strathfield",
    "2142": "Auburn / Granville",
    "2144": "Auburn",
    "2145": "Westmead / Parramatta",
    "2150": "Parramatta",
    "2153": "Baulkham Hills",
    "2154": "Castle Hill / Kellyville",
    "2155": "Kellyville / Rouse Hill",
    "2160": "Merrylands / Granville",
    "2170": "Liverpool",
    "2204": "Marrickville / Dulwich Hill",
    "2216": "Rockdale / Arncliffe",
    "2217": "Kogarah / Carlton",
    "2220": "Hurstville",
    "2228": "Miranda / Caringbah",
    "2230": "Cronulla / Caringbah South",
    "2232": "Sutherland / Engadine",
    "2560": "Campbelltown",
}
